# Generated by Django 3.2.7 on 2021-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211005_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.CharField(choices=[('KG', 'Kg'), ('NOS', 'Nos'), ('LITRE', 'Litre')], default='NOS', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
