# Generated by Django 3.2.7 on 2021-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_item_field_to_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
