# Generated by Django 3.2.7 on 2021-11-20 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211110_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
