# Generated by Django 3.2.7 on 2021-11-20 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211120_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('DAIRY', 'Dairy'), ('FRUITS', 'Fruits'), ('DAILY NEEDS', 'Daily Needs'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('units', models.CharField(choices=[('KG', 'Kg'), ('GRAM', 'Gram'), ('NOS', 'Nos'), ('LITRE', 'Litre')], default='NOS', max_length=10)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
