# Generated by Django 3.2.7 on 2021-11-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211121_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gm', 'Gm'), ('Units', 'Units'), ('L', 'L')], default='Units', max_length=10),
        ),
    ]
