# Generated by Django 3.2.7 on 2021-11-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20211127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('DAIRY', 'Dairy'), ('FRUITS', 'Fruits'), ('ESSENTIALS', 'Essentials')], default='ESSENTIALS', max_length=20),
        ),
    ]
