# Generated by Django 3.2.7 on 2021-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211128_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('DAIRY', 'Dairy'), ('BREADS', 'Breads'), ('OILS', 'Oils'), ('CREAMS', 'Creams')], default='DAIRY', max_length=20),
        ),
    ]
